/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.NurseRole;

import model.appointment.Appointment;
import model.Enterprise.Enterprise;
import model.Operation.Operation;
import model.Patient.Patient;
import model.UserAccount.UserAccount;
import model.WorkQueue.NurseWorkRequest;
import model.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sushmithaprathap
 */
public class NurseWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    //private DoctorOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;

    /**
     * Creates new form NurseWorkAreaJPanel
     */
    public NurseWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount ua) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = ua;
        //viewDetailsJPanel.setVisible(false);
        //searchJPanel.setVisible(false);
        enterpriseLabel.setText(enterprise.getOrgName());
        heading.setText("Welcome " + ua.getEmp().getNameVar());
        // requestTestJButton.setVisible(false);
    }

    public void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);
        for (WorkRequest request : enterprise.getOrgWq().getWorkRequestArray()) {

            if (request instanceof NurseWorkRequest) {
                Object[] row = new Object[11];
                row[0] = request.getSender();
                row[1] = request.getReceiver();
                row[2] = ((NurseWorkRequest) request).getPatient();
                row[3] = request.getStatus();
                Appointment app = ((NurseWorkRequest) request).getAppt();
                row[4] = app;//request.getMessage() == null ? " " : request.getMessage() ;
                row[5] = request;
                row[6] = request.getMsg();
                row[7] = app.getStatus();
                Operation opr = app.getOp() == null ? null : app.getOp();
                row[8] = opr.getStatus() == null ? "" : opr.getStatus();
                row[9] = opr.getOprType();
                row[10] = opr.getOpDate() == null ? "" : opr.getOpDate();
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        buttonPanel = new javax.swing.JPanel();
        viewReqBtn = new javax.swing.JButton();
        refreshTestJButton = new javax.swing.JButton();
        viewDetailsBtn = new javax.swing.JButton();
        btnManageBedAssngmt = new javax.swing.JButton();
        btnAssignToMe = new javax.swing.JButton();
        heading = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestJTable.setBackground(new java.awt.Color(236, 236, 236));
        workRequestJTable.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 204, 255)));
        workRequestJTable.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sender", "Receiver", "Patient", "Status", "Appointment Date", "Request ID", "Message", "Appointment Status", "Operation Status", "Operation Type", "Operation Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workRequestJTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 1088, 183));

        buttonPanel.setBackground(new java.awt.Color(236, 236, 236));

        viewReqBtn.setBackground(new java.awt.Color(9, 87, 136));
        viewReqBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        viewReqBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewReqBtn.setText("View New Request");
        viewReqBtn.setPreferredSize(new java.awt.Dimension(167, 40));
        viewReqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReqBtnActionPerformed(evt);
            }
        });

        refreshTestJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        refreshTestJButton.setForeground(new java.awt.Color(9, 87, 136));
        refreshTestJButton.setText("Refresh");
        refreshTestJButton.setPreferredSize(new java.awt.Dimension(167, 40));
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });

        viewDetailsBtn.setBackground(new java.awt.Color(9, 87, 136));
        viewDetailsBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        viewDetailsBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewDetailsBtn.setText("View Details");
        viewDetailsBtn.setPreferredSize(new java.awt.Dimension(167, 40));
        viewDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsBtnActionPerformed(evt);
            }
        });

        btnManageBedAssngmt.setBackground(new java.awt.Color(9, 87, 136));
        btnManageBedAssngmt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnManageBedAssngmt.setForeground(new java.awt.Color(255, 255, 255));
        btnManageBedAssngmt.setText("Manage Bed Assignment");
        btnManageBedAssngmt.setPreferredSize(new java.awt.Dimension(167, 40));
        btnManageBedAssngmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageBedAssngmtActionPerformed(evt);
            }
        });

        btnAssignToMe.setBackground(new java.awt.Color(9, 87, 136));
        btnAssignToMe.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAssignToMe.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignToMe.setText("Assign To Me");
        btnAssignToMe.setPreferredSize(new java.awt.Dimension(167, 40));
        btnAssignToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToMeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(viewReqBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(refreshTestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(viewDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnManageBedAssngmt, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnAssignToMe, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewReqBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshTestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageBedAssngmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAssignToMe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        add(buttonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 970, 120));

        heading.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        heading.setForeground(new java.awt.Color(68, 145, 157));
        heading.setText("Welcome!");
        add(heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 420, 37));

        enterpriseLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(68, 145, 157));
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 510, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed

        populateRequestTable();

    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void viewReqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReqBtnActionPerformed
        // TODO add your handling code here:
        //show all new request
        if (enterprise.getOrgWq().getWorkRequestArray().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No request!");
            return;

        }

        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);
        for (WorkRequest request : enterprise.getOrgWq().getWorkRequestArray()) {
            if ((request.getStatus().equals("New")) && (request instanceof NurseWorkRequest)) {

                //sender, receiver, pateint,status, message
                Object[] row = new Object[11];
                row[0] = request.getSender();
                row[1] = request.getReceiver();
                row[2] = ((NurseWorkRequest) request).getPatient();
                row[3] = request.getStatus();

                //String result = ((LabTestWorkRequest) request).getTestResult();
                //row[3] = result == null ? "Waiting" : result;
                Appointment app = ((NurseWorkRequest) request).getAppt();
                row[4] = app;//request.getMessage() == null ? " " : request.getMessage() ;
                row[5] = request;
                row[6] = request.getMsg();
                row[7] = app.getStatus();
                Operation opr = app.getOp() == null ? null : app.getOp();
                row[8] = opr.getStatus() == null ? "" : opr.getStatus();
                row[9] = opr.getOprType();
                row[10] = opr.getOpDate() == null ? "" : opr.getOpDate();
                model.addRow(row);

            }
        }

    }//GEN-LAST:event_viewReqBtnActionPerformed

    private void viewDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsBtnActionPerformed
        // TODO add your handling code here:
        //viewDetailsJPanel.setVisible(true);

        int row = workRequestJTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        UserAccount doctor = (UserAccount) workRequestJTable.getValueAt(row, 0);

        Patient patient = (Patient) workRequestJTable.getValueAt(row, 2);

        Appointment appointment = (Appointment) workRequestJTable.getValueAt(row, 4);
        //FlightSchedule fsch= (FlightSchedule)  tblFlightSchedule.getValueAt(row,7);
        UserAccount nurseUserAccount = userAccount;
        WorkRequest workreq = (WorkRequest) workRequestJTable.getValueAt(row, 5);

        if (workreq.getReceiver() == null) {
            JOptionPane.showMessageDialog(null, "Please assign request!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        AssignBedJPanel manageOrganizationJPanel = new AssignBedJPanel(userProcessContainer, enterprise, appointment, patient, doctor, nurseUserAccount, workreq);
        userProcessContainer.add("AssignBedJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewDetailsBtnActionPerformed

    private void btnManageBedAssngmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageBedAssngmtActionPerformed
        // TODO add your handling code here:

        CardLayout layout = (CardLayout) userProcessContainer.getLayout(); //JPanel,Enterprise,UserAccount
        userProcessContainer.add("ManageBedsFinalJPanel", new ManageBedsFinalJPanel(userProcessContainer, enterprise, userAccount));
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnManageBedAssngmtActionPerformed

    private void btnAssignToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToMeActionPerformed
        // TODO add your handling code here:

        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }

        WorkRequest request = (WorkRequest) workRequestJTable.getValueAt(selectedRow, 5);

        if (request.getReceiver() != null && request.getReceiver().equals(userAccount)) {
            JOptionPane.showMessageDialog(null, "Already handled, cannot assign!");
            return;

        }
        request.setReceiver(userAccount);
        request.setStatus("Pending");
        populateRequestTable();

        JOptionPane.showMessageDialog(null, "Assignment successful!");

    }//GEN-LAST:event_btnAssignToMeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignToMe;
    private javax.swing.JButton btnManageBedAssngmt;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel heading;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JButton viewDetailsBtn;
    private javax.swing.JButton viewReqBtn;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
