/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Doctor;

import model.appointment.Appointment;
import model.DB4OUtil.DB4OUtil;
import model.EcoSystem;
import model.Enterprise.Enterprise;
import model.Enterprise.Lab.Lab;
import model.Enterprise.Lab.LabTest;
import model.Enterprise.Lab.LabTestDirectory;
import model.Network.Network;
import model.Organization.Organization;
import model.Patient.Patient;
import model.Person.Person;
import model.UserAccount.UserAccount;
import model.WorkQueue.LabTechWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Suprith
 */
public class AssignLabTestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AssignLabTestJPanel
     */
    private JPanel userProcessContainer;
    private Patient patient;
    private Person person;
    private Appointment appointment;
    private LabTestDirectory labTestList;
    private Lab lab;
    private Network network;
    private UserAccount userAccount;
    private Organization organization;
    private Date createdOn;
    private EcoSystem system;

    public AssignLabTestJPanel(JPanel userProcessContainer, Patient patient, Appointment appointment, Network network, UserAccount userAccount, Organization organization, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.patient = patient;
        this.appointment = appointment;
        this.labTestList = appointment.getLabTestArray();
        this.network = network;
        this.userAccount = userAccount;
        this.organization = organization;
        this.system= system;
        populateNetworkLabs();
        populateLabTest();
    }

    void populateNetworkLabs() {
        cmbLabs.removeAllItems();;
        if(system.getNetworkArray() == null)
        {
            return;
        }
        for(Network network1: system.getNetworkArray())
        {
         

        List<Enterprise> enterprsList = network1.getEnterpriseDir().getEnterpriseArray();
        if (enterprsList == null || enterprsList.isEmpty()) {
            //nothing
        } else {
            for (Enterprise enterprise : enterprsList) {
                if (enterprise.getTypeEnterprise().getValue().equals(Enterprise.EnterpriseType.Lab.getValue())) {
                    {
                        cmbLabs.addItem(enterprise);
                    }
                }
            }

        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        assignTestTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        testTypeTxt = new javax.swing.JTextField();
        cmbLabs = new javax.swing.JComboBox();
        submitBtn = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        assignTestTbl.setBackground(new java.awt.Color(236, 236, 236));
        assignTestTbl.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 204, 255)));
        assignTestTbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        assignTestTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date", "Test Name", "Lab ", "Patient Name", "Test Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(assignTestTbl);
        if (assignTestTbl.getColumnModel().getColumnCount() > 0) {
            assignTestTbl.getColumnModel().getColumn(0).setResizable(false);
            assignTestTbl.getColumnModel().getColumn(1).setResizable(false);
            assignTestTbl.getColumnModel().getColumn(2).setResizable(false);
            assignTestTbl.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(9, 87, 136));
        jLabel1.setText("Assign Lab Test");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Test Name :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Lab :");

        testTypeTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        testTypeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testTypeTxtActionPerformed(evt);
            }
        });

        cmbLabs.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmbLabs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbLabs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLabsActionPerformed(evt);
            }
        });

        submitBtn.setBackground(new java.awt.Color(9, 87, 136));
        submitBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitBtn.setText("Submit");
        submitBtn.setPreferredSize(new java.awt.Dimension(100, 40));
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        backJButton.setForeground(new java.awt.Color(9, 87, 136));
        backJButton.setText("Back");
        backJButton.setPreferredSize(new java.awt.Dimension(100, 40));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Images/lab.jpeg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(311, 311, 311)
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addGap(117, 117, 117)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(testTypeTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbLabs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(154, 154, 154))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22))))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(testTypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbLabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel2)))
                        .addGap(53, 53, 53)
                        .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                        .addGap(436, 436, 436))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void testTypeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testTypeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testTypeTxtActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        String testType = testTypeTxt.getText();
        //String labName = cmbLabs.getActionCommand();

        //String medsPrescribed= medsPrescribedTxt.getText();
        if (testType.equals("")) {
            JOptionPane.showMessageDialog(null, "Test Name cannot be empty");
        }   else
        { LabTechWorkRequest workreq = new LabTechWorkRequest();
                workreq.setStatus("New");
                appointment.setStatus(Appointment.AppointmentStatus.MarkforTest.getValue());
                workreq.setMsg("New Patient for Lab test, please confirm a Test Date");
                workreq.setStatus("New");
                workreq.setAppt(appointment);
                workreq.setMsg("Please conduct lab test!");
                workreq.setReqDate(createdOn == null ? new Date() : createdOn);
                //workreq.setDoctorUserAccount(userAccount);
                workreq.setSender(userAccount);
                workreq.setPatient(patient);
                //workreq.setDoctor(doctor);
                //workreq.setReceiver(userAccount);
                Lab lab = (Lab) cmbLabs.getSelectedItem();
                lab.getOrgWq().getWorkRequestArray().add(workreq);
                LabTest labTest= new LabTest();
                labTest.setLab(lab);
                labTest.setLabTech(null);
                labTest.setPatient(patient);
                labTest.setNameVar(testType);
                labTest.setDoc(appointment.getDoc());
                labTest.setStatusVar("New");
                //labTest.setType(testType);
                workreq.setLabTest(labTest);
                appointment.getLabTestArray().addLabTest(labTest);
                appointment.setStatus(Appointment.AppointmentStatus.MarkforTest.getValue());
                DB4OUtil.getInstance().storeSystem(system);
                //UserAccount recepUseracc = null;
                //List<UserAccount> userAccDir=  organization.getUserAccountDirectory().getUserAccountList();
                //List<UserAccount> nurseList = enterprise.getUserAccountDirectory().getUserAccountList();
                //workreq.setReceiver(lab.getUserAccountDirectory().getUserAccountList().get(0));
   }
        populateLabTest();
        //String medsPrescribed= medsPrescribedTxt.getText();
//        if (testType.equals("") || labName.equals("")) {
//            JOptionPane.showMessageDialog(null, "Fields cannot be empty");
//        } else {
//            LabTest labTest = labTestList.addLabTest();
//            labTest.setPatient(patient);
//            labTest.setType(testType);
//            labTest.setLab(lab);
//            //dateTxt.setText("");
//            testTypeTxt.setText("");
//            cmbLabs.setActionCommand(labName);
//            //medsPrescribedTxt.setText("");
//            //appointment.setLabTestList(labTestList);
//            JOptionPane.showMessageDialog(null, "Lab test assigned sucessfully");

//        }
    }//GEN-LAST:event_submitBtnActionPerformed

    public void populateLabTest() {
        DefaultTableModel model = (DefaultTableModel) assignTestTbl.getModel();
        model.setRowCount(0);
        //for (UserAccount ua : system.getUserAccountDirectory().getUserAccountList()) {s
        if(labTestList==null)
        {
            labTestList= new LabTestDirectory();
            appointment.setLabTestArray(labTestList);
        }
        if(labTestList.getLabTestArray() != null && !labTestList.getLabTestArray().isEmpty()){
        for (LabTest labTest : labTestList.getLabTestArray()) {
            Object[] row = new Object[5];
            row[0] = new Date();
            row[1] = labTest.getNameVar();
            row[2] = labTest.getLab();
            row[3] = labTest.getPatient();
            row[4] = (labTest.getStatusVar().equals("") ) ? "New" :labTest.getStatusVar() ;
            model.addRow(row);
            
        }
        }
    }
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
          Component [] componentArray = userProcessContainer.getComponents();
        Component c = componentArray[componentArray.length-1];
        DoctorWorkAreaJPanel ms = (DoctorWorkAreaJPanel) c;
        ms.populateRequestTable();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void cmbLabsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLabsActionPerformed
        String str = String.valueOf(cmbLabs.getSelectedItem());
    }//GEN-LAST:event_cmbLabsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable assignTestTbl;
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox cmbLabs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField testTypeTxt;
    // End of variables declaration//GEN-END:variables
}
