/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JCheckBox;

/**
 *
 * @author harshitaranganath
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private String username;
    private String password;

    public Main() {
        initComponents();
       
    }
  

    /* private Boolean checkBlankInput() {
        if (txtuname.getText().length() == 0 || txtpassword.getPassword().length == 0 || (chkbxSysAdmin.getText().length() == 0 && chkbxHospAdmin.getText().length() == 0 && chkbxPatient.getText().length() == 0 && chkbxDoctor.getText().length() == 0 && chkbxCommAdmin.getText().length() == 0)) {
            return false;
        } else {
            return true;
        }
    }

    /*private Boolean checkcred() {
        //CredentialDirectory allcredentials = new CredentialDirectory();
        String username = txtuname.getText();
        String password = String.valueOf(txtpassword.getPassword());
        if (chkbxSysAdmin.isSelected()) {
            String role = chkbxSysAdmin.getText();
            ArrayList<Credentials> idcheck = allcredentials.searchCredentials(username, password, role);
            if (allcredentials.checkSysAdminCred(username, password, role)) {
                return true;
            } else {
                return false;
            }
        } else if (chkbxPatient.isSelected()) {
            String role = chkbxPatient.getText();
            ArrayList<Credentials> idcheck = allcredentials.searchCredentials(username, password, role);
            if (idcheck.contains(username) && idcheck.contains(password) && idcheck.contains(role)) {
                return true;
            } else {
                return false;
            }
        } else if (chkbxCommAdmin.isSelected()) {

            String role = chkbxCommAdmin.getText();
            boolean idcheck = allcredentials.checkCommAdminCred(username, password, role);
            if (idcheck) {
                return true;
            } else {
                return false;
            }
        } else if (chkbxDoctor.isSelected()) {
            String role = chkbxDoctor.getText();
            ArrayList<Credentials> idcheck = allcredentials.searchCredentials(username, password, role);
            if (idcheck.contains(username) && idcheck.contains(password) && idcheck.contains(role)) {
                return true;
            } else {
                return false;
            }
        } else if (chkbxHospAdmin.isSelected()) {
            String role = chkbxHospAdmin.getText();
            ArrayList<Credentials> idcheck = allcredentials.searchCredentials(username, password, role);
            if (idcheck.contains(username) && idcheck.contains(password) && idcheck.contains(role)) {
                return true;
            } else {
                return false;
            }
        } else {
            return false;
        }

    }

    public String getuname() {
        return String.valueOf(txtuname.getText());
    }

    public String getpass() {
        return String.valueOf(txtpassword.getPassword());
    }

    public String getrole() {
        if (chkbxDoctor.isSelected()) {
            return chkbxDoctor.getText();
        } else if (chkbxCommAdmin.isSelected()) {
            return chkbxCommAdmin.getText();
        } else if (chkbxPatient.isSelected()) {
            return chkbxPatient.getText();
        } else if (chkbxHospAdmin.isSelected()) {
            return chkbxHospAdmin.getText();
        } else {
            return chkbxSysAdmin.getText();
        }
    }

    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);

    }

    private boolean checkbox() {
        JCheckBox[] newList = new JCheckBox[5];
        newList[0] = chkbxCommAdmin;
        newList[1] = chkbxHospAdmin;
        newList[2] = chkbxDoctor;
        newList[3] = chkbxPatient;
        newList[4] = chkbxSysAdmin;
        int k = 0;
        for (int i = 0; i < newList.length; i++) {
            if (newList[i].isSelected()) {
                k += 1;
            }
        }
        if (k == 1) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DonateBtn1 = new javax.swing.JButton();
        VolunteerBtn = new javax.swing.JButton();
        NeedFoodBtn = new javax.swing.JButton();
        DonateBtn2 = new javax.swing.JButton();
        AboutUsBtn = new javax.swing.JButton();
        CareersBtn = new javax.swing.JButton();
        LoginHero = new javax.swing.JLabel();
        FooterText = new javax.swing.JLabel();
        HeroFooter = new javax.swing.JLabel();
        LoginComboBox = new javax.swing.JComboBox<>();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Page");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setForeground(new java.awt.Color(0, 102, 255));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Login");
        mainPanel.add(jLabel4);

        jLabel3.setText("jLabel3");
        mainPanel.add(jLabel3);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel10.setText("Mass General Hospital");
        mainPanel.add(jLabel10);

        loginPanel.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, -160, 990, 70));

        jLabel6.setFont(new java.awt.Font("Kodchasan", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(23, 143, 206));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/logo.png"))); // NOI18N
        jLabel6.setText("Charity-Eco");
        jLabel6.setToolTipText("Name");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        loginPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 130));

        DonateBtn1.setBackground(new java.awt.Color(59, 135, 211));
        DonateBtn1.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        DonateBtn1.setForeground(new java.awt.Color(255, 255, 255));
        DonateBtn1.setText("Gift a smile!");
        DonateBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonateBtn1ActionPerformed(evt);
            }
        });
        loginPanel.add(DonateBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 50, 170, 50));

        VolunteerBtn.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        VolunteerBtn.setForeground(new java.awt.Color(59, 135, 211));
        VolunteerBtn.setText("Volunteer");
        VolunteerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolunteerBtnActionPerformed(evt);
            }
        });
        loginPanel.add(VolunteerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 120, 50));

        NeedFoodBtn.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        NeedFoodBtn.setForeground(new java.awt.Color(59, 135, 211));
        NeedFoodBtn.setText("Need Food?");
        NeedFoodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NeedFoodBtnActionPerformed(evt);
            }
        });
        loginPanel.add(NeedFoodBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 50, 120, 50));

        DonateBtn2.setBackground(new java.awt.Color(204, 153, 0));
        DonateBtn2.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        DonateBtn2.setForeground(new java.awt.Color(255, 255, 255));
        DonateBtn2.setText("Donate Now!");
        DonateBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonateBtn2ActionPerformed(evt);
            }
        });
        loginPanel.add(DonateBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 460, 150, 50));

        AboutUsBtn.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        AboutUsBtn.setForeground(new java.awt.Color(59, 135, 211));
        AboutUsBtn.setText("About us");
        AboutUsBtn.setAlignmentY(0.0F);
        AboutUsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AboutUsBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AboutUsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsBtnActionPerformed(evt);
            }
        });
        loginPanel.add(AboutUsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 120, 50));

        CareersBtn.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        CareersBtn.setForeground(new java.awt.Color(59, 135, 211));
        CareersBtn.setText("Careers");
        CareersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CareersBtnActionPerformed(evt);
            }
        });
        loginPanel.add(CareersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 120, 50));

        LoginHero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/bg.jpeg"))); // NOI18N
        loginPanel.add(LoginHero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1420, 580));

        FooterText.setBackground(new java.awt.Color(204, 204, 204));
        FooterText.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 3, 18)); // NOI18N
        FooterText.setForeground(new java.awt.Color(59, 135, 211));
        FooterText.setText("   Address: The Boston Food Bank, 70 South Bay Avenue Boston, MA 02118               Phone: 617.427.5200                 Email: bostonfoodbank@gmail.com");
        loginPanel.add(FooterText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 1420, 70));

        HeroFooter.setForeground(new java.awt.Color(255, 255, 255));
        loginPanel.add(HeroFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1410, 640));

        LoginComboBox.setFont(new java.awt.Font("Khmer MN", 0, 18)); // NOI18N
        LoginComboBox.setForeground(new java.awt.Color(59, 135, 211));
        LoginComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Login", "Corporate Login", "Employee Login", "Supervisor Login", "Admin Login" }));
        LoginComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginComboBoxActionPerformed(evt);
            }
        });
        loginPanel.add(LoginComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 50, 220, 50));

        getContentPane().add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 790));

        setSize(new java.awt.Dimension(1415, 812));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DonateBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonateBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DonateBtn1ActionPerformed

    private void VolunteerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolunteerBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VolunteerBtnActionPerformed

    private void NeedFoodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NeedFoodBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NeedFoodBtnActionPerformed

    private void DonateBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonateBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DonateBtn2ActionPerformed

    private void AboutUsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutUsBtnActionPerformed

    private void CareersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CareersBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CareersBtnActionPerformed

    private void LoginComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginComboBoxActionPerformed
        // TODO add your handling code here:
        int id = evt.getID();
        System.out.println(id);
        SupervisorLogin suplogin = new SupervisorLogin();
        JFrame frame = new JFrame();
         frame.setPreferredSize(new Dimension(1070, 600));
        frame.setSize(900, 600);
        frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        frame.setVisible(true);
        frame.getContentPane().add(suplogin);
        frame.setVisible(true);

        new Main().setVisible(false);
        
        frame.setPreferredSize(new Dimension(1070, 600));

        frame.setSize(1070, 600);
        frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        frame.setVisible(true);
        frame.setVisible(true);
    }//GEN-LAST:event_LoginComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutUsBtn;
    private javax.swing.JButton CareersBtn;
    private javax.swing.JButton DonateBtn1;
    private javax.swing.JButton DonateBtn2;
    private javax.swing.JLabel FooterText;
    private javax.swing.JLabel HeroFooter;
    private javax.swing.JComboBox<String> LoginComboBox;
    private javax.swing.JLabel LoginHero;
    private javax.swing.JButton NeedFoodBtn;
    private javax.swing.JButton VolunteerBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

}
