

package UI.AdminRole;

import model.EcoSystem;
import model.Enterprise.Enterprise;
import model.Organization.BedMgmtDept;
import model.Organization.Organization;
import model.Organization.OrganizationDirectory;
import model.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author  Suprith
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    UserAccount account;
    Organization organization;
    EcoSystem system;
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise,UserAccount account, Organization organization, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account = account;
        this.organization = organization;
        this.system = system;
        lblEnterprise.setText(enterprise.getOrgName());
        lblHeading.setText("Welcome " + account.getEmp().getNameVar());
        String enterpriseType= enterprise.getTypeEnterprise().toString();
        if(enterpriseType.equals("Hospital"))
        {
            btnManageBed.setEnabled(true);
            btnManageBed.setVisible(true);
        }
        else{
             btnManageBed.setEnabled(false);
             btnManageBed.setVisible(false);
        }
        
        
        if(enterpriseType.equals("Pharmacy"))
        {            
            btnManageInv.setVisible(true);
            btnManageInv.setEnabled(true);
        }
        else{
            btnManageInv.setVisible(false);
            btnManageInv.setEnabled(false);
        }
        
        if(enterpriseType.equals("Hospital"))
        {        
        lblEnterpriseImage.setIcon(new ImageIcon("src/UI/Images/admin.jpeg"));
        }
        else if(enterpriseType.equals("Pharmacy"))
        {        
        lblEnterpriseImage.setIcon(new ImageIcon("src/UI/Images/pharmacy.jpeg"));
        }
        else if(enterpriseType.equals("Lab"))
        {        
        lblEnterpriseImage.setIcon(new ImageIcon("src/UI/Images/lab.jpeg"));
        }   
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEnterprise = new javax.swing.JLabel();
        lblButtons = new javax.swing.JPanel();
        btnManageDept = new javax.swing.JButton();
        btnManageStaff = new javax.swing.JButton();
        btnManageBed = new javax.swing.JButton();
        btnManageInv = new javax.swing.JButton();
        lblHeading = new javax.swing.JLabel();
        lblEnterpriseImage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEnterprise.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblEnterprise.setForeground(new java.awt.Color(68, 145, 157));
        lblEnterprise.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 280, 30));

        lblButtons.setBackground(new java.awt.Color(255, 255, 255));
        lblButtons.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 204, 255)));
        lblButtons.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageDept.setBackground(new java.awt.Color(9, 87, 136));
        btnManageDept.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnManageDept.setForeground(new java.awt.Color(255, 255, 255));
        btnManageDept.setText("Manage Department");
        btnManageDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDeptActionPerformed(evt);
            }
        });
        lblButtons.add(btnManageDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 320, 70));

        btnManageStaff.setBackground(new java.awt.Color(9, 87, 136));
        btnManageStaff.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnManageStaff.setForeground(new java.awt.Color(255, 255, 255));
        btnManageStaff.setText("Manage Staff");
        btnManageStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStaffActionPerformed(evt);
            }
        });
        lblButtons.add(btnManageStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 320, 70));

        btnManageBed.setBackground(new java.awt.Color(9, 87, 136));
        btnManageBed.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnManageBed.setForeground(new java.awt.Color(255, 255, 255));
        btnManageBed.setText("Manage Bed");
        btnManageBed.setEnabled(false);
        btnManageBed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageBedActionPerformed(evt);
            }
        });
        lblButtons.add(btnManageBed, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 320, 70));

        btnManageInv.setBackground(new java.awt.Color(9, 87, 136));
        btnManageInv.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnManageInv.setForeground(new java.awt.Color(255, 255, 255));
        btnManageInv.setText("Manage Inventory");
        btnManageInv.setEnabled(false);
        btnManageInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageInvActionPerformed(evt);
            }
        });
        lblButtons.add(btnManageInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 320, 70));

        add(lblButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 440, 420));

        lblHeading.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(9, 87, 136));
        lblHeading.setText("Welcome Admin");
        add(lblHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 360, 37));

        lblEnterpriseImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Images/admin.jpeg"))); // NOI18N
        add(lblEnterpriseImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 580, 560));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStaffActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(userProcessContainer, enterprise, system);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageStaffActionPerformed

    private void btnManageInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageInvActionPerformed

        ManageMedicinesJPanel manageEmployeeJPanel = new ManageMedicinesJPanel(userProcessContainer, enterprise.getOrgDir(), enterprise);
        userProcessContainer.add("ManageMedicinesJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnManageInvActionPerformed

    private void btnManageDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDeptActionPerformed

        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(userProcessContainer, enterprise.getOrgDir(), enterprise, system);
        userProcessContainer.add("ManageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageDeptActionPerformed

    private void btnManageBedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageBedActionPerformed
        // TODO add your handling code here:
        //check if bed management department is created or not
        boolean flag=false;
        BedMgmtDept bedOrg=null;
        OrganizationDirectory orgDir = enterprise.getOrgDir();
        for(Organization org : orgDir.getOrganizationArray() ){
            if(org.getOrgName().equals(Organization.Type.BedManagement.getValueVar()))
            {
                //if bed management departemtn is present then navigate to bed management screen
                flag = true;
                bedOrg = (BedMgmtDept)org;
            }
        }
        
        if(flag == true){
        ManageBedJPanel manageOrganizationJPanel = new ManageBedJPanel(userProcessContainer, 
                orgDir, organization, bedOrg, enterprise,system);
        userProcessContainer.add("ManageBedJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        
        else{
            JOptionPane.showMessageDialog(null, "No Bed Management department, please create one!");
            return;

        }
    }//GEN-LAST:event_btnManageBedActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageBed;
    private javax.swing.JButton btnManageDept;
    private javax.swing.JButton btnManageInv;
    private javax.swing.JButton btnManageStaff;
    private javax.swing.JPanel lblButtons;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblEnterpriseImage;
    private javax.swing.JLabel lblHeading;
    // End of variables declaration//GEN-END:variables
    
}
